name: Upload objdiff report

on:
  push:
    branches:
      - main
      - progress

jobs:
  report-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U -r requirements.txt

      - name: Setup wine
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install wine32

      - name: Setup build environment
        run: |
          sudo apt-get install binutils-mips-linux-gnu
          scripts/setup_progd_linux.sh
          curl -o disc/SCUS_971.98 "${{ secrets.FILE_URL }}"

      - name: Configure and generate report
        run: |
          python configure.py --objects
          ninja
          ./tools/objdiff/objdiff-cli report generate > report.json

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SCUS_971.98_report
          path: ./report.json
